# used for local testing
version: '3.8'
services:
  redis:
    image: redis:6.2.12-alpine3.17
    ports:
      - '6379:6379'
  slike:
    image: slike
    volumes:
      - ./web/dist:/sanic/web
    ports:
      - 80:8000
    env_file:
      - .dev-secrets.env